version: 2

jobs:
  test-debug:
    docker:
      - image: rikorose/gcc-cmake
    steps:
      - checkout
      - run:
          command: |
            git submodule update --init --recursive --remote
            cd test            
            mkdir build-debug
            cd build-debug
            cmake .. -DCMAKE_BUILD_TYPE=Debug
            make
            make test

workflows:
  version: 2
  build:
    jobs:
      - test-debug
